<?php

namespace Database\Seeders;

use App\Models\Property;
use App\Models\PropertyImage;
use App\Models\PropertyFeature;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        $properties = [
            // Rent - Apartments
            [
                'title_en' => 'Modern 2-Bedroom Apartment in Malabata',
                'title_fr' => 'Appartement moderne 2 chambres à Malabata',
                'description_en' => 'Beautiful modern apartment with sea views, fully furnished with high-end finishes. Located in the prestigious Malabata area with easy access to beaches and amenities.',
                'description_fr' => 'Bel appartement moderne avec vue mer, entièrement meublé avec des finitions haut de gamme. Situé dans le quartier prestigieux de Malabata avec accès facile aux plages et commodités.',
                'price' => 8500,
                'transaction_type' => 'rent',
                'property_type' => 'apartment',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area_sqm' => 85,
                'floor' => '3rd',
                'furnished' => 'furnished',
                'city' => 'Tangier',
                'neighborhood' => 'Malabata',
                'latitude' => 35.7895,
                'longitude' => -5.7892,
                'featured' => true,
                'status' => 'published',
            ],
            [
                'title_en' => 'Cozy Studio Near City Center',
                'title_fr' => 'Studio cosy près du centre-ville',
                'description_en' => 'Perfect starter home or investment property. This studio apartment is located in the heart of Tangier with all amenities within walking distance.',
                'description_fr' => 'Parfait pour un premier logement ou investissement. Ce studio est situé au coeur de Tanger avec toutes les commodités à distance de marche.',
                'price' => 4500,
                'transaction_type' => 'rent',
                'property_type' => 'studio',
                'bedrooms' => 0,
                'bathrooms' => 1,
                'area_sqm' => 35,
                'floor' => '2nd',
                'furnished' => 'furnished',
                'city' => 'Tangier',
                'neighborhood' => 'Centre Ville',
                'latitude' => 35.7673,
                'longitude' => -5.7998,
                'featured' => false,
                'status' => 'published',
            ],
            [
                'title_en' => 'Luxury 3-Bedroom Apartment with Terrace',
                'title_fr' => 'Appartement de luxe 3 chambres avec terrasse',
                'description_en' => 'Exceptional luxury apartment featuring a large private terrace with panoramic views. High-end kitchen, marble floors, and premium fixtures throughout.',
                'description_fr' => 'Appartement de luxe exceptionnel avec grande terrasse privée et vue panoramique. Cuisine haut de gamme, sols en marbre et équipements premium.',
                'price' => 15000,
                'transaction_type' => 'rent',
                'property_type' => 'apartment',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area_sqm' => 150,
                'floor' => '5th',
                'furnished' => 'furnished',
                'city' => 'Tangier',
                'neighborhood' => 'Cap Spartel',
                'latitude' => 35.7862,
                'longitude' => -5.9283,
                'featured' => true,
                'status' => 'published',
            ],

            // Rent - Houses/Villas
            [
                'title_en' => 'Traditional Riad in Kasbah',
                'title_fr' => 'Riad traditionnel dans la Kasbah',
                'description_en' => 'Authentic Moroccan riad in the historic Kasbah district. Features traditional architecture, courtyard garden, and rooftop terrace with stunning views.',
                'description_fr' => 'Riad marocain authentique dans le quartier historique de la Kasbah. Architecture traditionnelle, jardin intérieur et terrasse sur le toit avec vue imprenable.',
                'price' => 12000,
                'transaction_type' => 'rent',
                'property_type' => 'house',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area_sqm' => 200,
                'floor' => null,
                'furnished' => 'furnished',
                'city' => 'Tangier',
                'neighborhood' => 'Kasbah',
                'latitude' => 35.7873,
                'longitude' => -5.8133,
                'featured' => true,
                'status' => 'published',
            ],
            [
                'title_en' => 'Beachfront Villa in Asilah',
                'title_fr' => 'Villa en bord de mer à Asilah',
                'description_en' => 'Stunning beachfront villa with direct beach access. Perfect for families seeking luxury coastal living in the charming town of Asilah.',
                'description_fr' => 'Magnifique villa en bord de mer avec accès direct à la plage. Parfait pour les familles recherchant un mode de vie côtier de luxe à Asilah.',
                'price' => 25000,
                'transaction_type' => 'rent',
                'property_type' => 'villa',
                'bedrooms' => 5,
                'bathrooms' => 4,
                'area_sqm' => 350,
                'floor' => null,
                'furnished' => 'furnished',
                'city' => 'Asilah',
                'neighborhood' => 'Beachfront',
                'latitude' => 35.4652,
                'longitude' => -6.0356,
                'featured' => true,
                'status' => 'published',
            ],

            // Sale - Apartments
            [
                'title_en' => 'New Build Apartment in Iberia',
                'title_fr' => 'Appartement neuf à Iberia',
                'description_en' => 'Brand new apartment in the developing Iberia district. Modern construction with quality finishes, parking space included. Great investment opportunity.',
                'description_fr' => 'Appartement neuf dans le quartier Iberia en développement. Construction moderne avec finitions de qualité, place de parking incluse. Excellente opportunité d\'investissement.',
                'price' => 850000,
                'transaction_type' => 'sale',
                'property_type' => 'apartment',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area_sqm' => 75,
                'floor' => '4th',
                'furnished' => 'unfurnished',
                'city' => 'Tangier',
                'neighborhood' => 'Iberia',
                'latitude' => 35.7612,
                'longitude' => -5.8234,
                'featured' => false,
                'status' => 'published',
            ],
            [
                'title_en' => 'Penthouse with Sea Views in Tangier Bay',
                'title_fr' => 'Penthouse avec vue mer sur la Baie de Tanger',
                'description_en' => 'Exceptional penthouse offering breathtaking views of the Mediterranean and the strait of Gibraltar. Spacious terrace, premium finishes, private elevator access.',
                'description_fr' => 'Penthouse exceptionnel offrant une vue imprenable sur la Méditerranée et le détroit de Gibraltar. Grande terrasse, finitions premium, accès ascenseur privé.',
                'price' => 3500000,
                'transaction_type' => 'sale',
                'property_type' => 'apartment',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area_sqm' => 250,
                'floor' => '10th',
                'furnished' => 'semi-furnished',
                'city' => 'Tangier',
                'neighborhood' => 'Tangier Bay',
                'latitude' => 35.7789,
                'longitude' => -5.8012,
                'featured' => true,
                'status' => 'published',
            ],
            [
                'title_en' => 'Family Apartment in Mesnana',
                'title_fr' => 'Appartement familial à Mesnana',
                'description_en' => 'Spacious family apartment in quiet residential area. Close to international schools and shopping centers. Secure building with parking.',
                'description_fr' => 'Appartement familial spacieux dans un quartier résidentiel calme. Proche des écoles internationales et centres commerciaux. Immeuble sécurisé avec parking.',
                'price' => 1200000,
                'transaction_type' => 'sale',
                'property_type' => 'apartment',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area_sqm' => 120,
                'floor' => '2nd',
                'furnished' => 'unfurnished',
                'city' => 'Tangier',
                'neighborhood' => 'Mesnana',
                'latitude' => 35.7534,
                'longitude' => -5.8567,
                'featured' => false,
                'status' => 'published',
            ],

            // Sale - Villas
            [
                'title_en' => 'Modern Villa with Pool in Achakar',
                'title_fr' => 'Villa moderne avec piscine à Achakar',
                'description_en' => 'Contemporary villa with infinity pool overlooking the Atlantic. Smart home features, landscaped garden, double garage. The epitome of luxury living.',
                'description_fr' => 'Villa contemporaine avec piscine à débordement sur l\'Atlantique. Domotique, jardin paysager, double garage. L\'incarnation du luxe.',
                'price' => 5500000,
                'transaction_type' => 'sale',
                'property_type' => 'villa',
                'bedrooms' => 5,
                'bathrooms' => 4,
                'area_sqm' => 400,
                'floor' => null,
                'furnished' => 'semi-furnished',
                'city' => 'Tangier',
                'neighborhood' => 'Achakar',
                'latitude' => 35.7623,
                'longitude' => -5.9123,
                'featured' => true,
                'status' => 'published',
            ],
            [
                'title_en' => 'Charming House in Marshan',
                'title_fr' => 'Charmante maison à Marshan',
                'description_en' => 'Character house in the historic Marshan neighborhood. Garden, rooftop terrace, sea views. Perfect blend of traditional charm and modern comfort.',
                'description_fr' => 'Maison de caractère dans le quartier historique de Marshan. Jardin, terrasse sur le toit, vue mer. Mélange parfait de charme traditionnel et confort moderne.',
                'price' => 2800000,
                'transaction_type' => 'sale',
                'property_type' => 'house',
                'bedrooms' => 4,
                'bathrooms' => 2,
                'area_sqm' => 180,
                'floor' => null,
                'furnished' => 'unfurnished',
                'city' => 'Tangier',
                'neighborhood' => 'Marshan',
                'latitude' => 35.7867,
                'longitude' => -5.8234,
                'featured' => false,
                'status' => 'published',
            ],

            // Sale - Land
            [
                'title_en' => 'Building Plot in Charf',
                'title_fr' => 'Terrain constructible à Charf',
                'description_en' => 'Prime building land in the developing Charf area. Flat terrain, all utilities available. Ideal for residential or small commercial project.',
                'description_fr' => 'Terrain de premier choix dans le quartier en développement de Charf. Terrain plat, tous les raccordements disponibles. Idéal pour projet résidentiel ou petit commercial.',
                'price' => 1500000,
                'transaction_type' => 'sale',
                'property_type' => 'land',
                'bedrooms' => null,
                'bathrooms' => null,
                'area_sqm' => 500,
                'floor' => null,
                'furnished' => null,
                'city' => 'Tangier',
                'neighborhood' => 'Charf',
                'latitude' => 35.7456,
                'longitude' => -5.8712,
                'featured' => false,
                'status' => 'published',
            ],
            [
                'title_en' => 'Agricultural Land Near Asilah',
                'title_fr' => 'Terrain agricole près d\'Asilah',
                'description_en' => 'Large agricultural plot with water access, suitable for farming or eco-tourism project. Beautiful countryside location with development potential.',
                'description_fr' => 'Grande parcelle agricole avec accès à l\'eau, adaptée à l\'agriculture ou projet éco-touristique. Belle situation campagnarde avec potentiel de développement.',
                'price' => 2000000,
                'transaction_type' => 'sale',
                'property_type' => 'farm',
                'bedrooms' => null,
                'bathrooms' => null,
                'area_sqm' => 10000,
                'floor' => null,
                'furnished' => null,
                'city' => 'Asilah',
                'neighborhood' => 'Rural',
                'latitude' => 35.4823,
                'longitude' => -6.0012,
                'featured' => false,
                'status' => 'published',
            ],

            // Commercial
            [
                'title_en' => 'Prime Retail Space in Tangier City Mall',
                'title_fr' => 'Local commercial prime au Tangier City Mall',
                'description_en' => 'High-traffic retail space in the popular Tangier City Mall. Ideal for fashion, electronics, or service business. Includes storage and utilities.',
                'description_fr' => 'Local commercial à fort trafic dans le populaire Tangier City Mall. Idéal pour mode, électronique ou services. Comprend stockage et charges.',
                'price' => 35000,
                'transaction_type' => 'commercial',
                'property_type' => 'shop',
                'bedrooms' => null,
                'bathrooms' => 1,
                'area_sqm' => 80,
                'floor' => 'Ground',
                'furnished' => 'unfurnished',
                'city' => 'Tangier',
                'neighborhood' => 'Tangier City Mall',
                'latitude' => 35.7534,
                'longitude' => -5.8234,
                'featured' => false,
                'status' => 'published',
            ],
            [
                'title_en' => 'Modern Office Space in Business District',
                'title_fr' => 'Bureau moderne dans le quartier d\'affaires',
                'description_en' => 'Contemporary office space in Tangier\'s growing business district. Open plan layout, meeting rooms, high-speed internet, 24/7 access.',
                'description_fr' => 'Espace de bureau contemporain dans le quartier d\'affaires en croissance de Tanger. Plan ouvert, salles de réunion, internet haut débit, accès 24/7.',
                'price' => 18000,
                'transaction_type' => 'commercial',
                'property_type' => 'office',
                'bedrooms' => null,
                'bathrooms' => 2,
                'area_sqm' => 150,
                'floor' => '3rd',
                'furnished' => 'semi-furnished',
                'city' => 'Tangier',
                'neighborhood' => 'Business District',
                'latitude' => 35.7623,
                'longitude' => -5.8345,
                'featured' => true,
                'status' => 'published',
            ],
            [
                'title_en' => 'Garage Workshop Space',
                'title_fr' => 'Espace atelier garage',
                'description_en' => 'Large garage space suitable for auto repair, storage, or workshop. High ceiling, vehicle access, electricity and water connected.',
                'description_fr' => 'Grand espace garage adapté à la réparation auto, stockage ou atelier. Haute plafond, accès véhicule, électricité et eau raccordées.',
                'price' => 8000,
                'transaction_type' => 'commercial',
                'property_type' => 'garage',
                'bedrooms' => null,
                'bathrooms' => 1,
                'area_sqm' => 200,
                'floor' => 'Ground',
                'furnished' => 'unfurnished',
                'city' => 'Tangier',
                'neighborhood' => 'Industrial Zone',
                'latitude' => 35.7423,
                'longitude' => -5.8712,
                'featured' => false,
                'status' => 'published',
            ],

            // More Rent properties
            [
                'title_en' => 'Furnished Apartment Near Train Station',
                'title_fr' => 'Appartement meublé près de la gare',
                'description_en' => 'Convenient location near Tangier Ville train station. Ideal for professionals or students. All utilities included in rent.',
                'description_fr' => 'Emplacement pratique près de la gare Tanger Ville. Idéal pour professionnels ou étudiants. Toutes charges comprises.',
                'price' => 5500,
                'transaction_type' => 'rent',
                'property_type' => 'apartment',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'area_sqm' => 55,
                'floor' => '1st',
                'furnished' => 'furnished',
                'city' => 'Tangier',
                'neighborhood' => 'Gare Tanger Ville',
                'latitude' => 35.7567,
                'longitude' => -5.8123,
                'featured' => false,
                'status' => 'published',
            ],
            [
                'title_en' => 'Seaside Apartment in Martil',
                'title_fr' => 'Appartement bord de mer à Martil',
                'description_en' => 'Charming seaside apartment in the popular beach town of Martil. Perfect for summer rentals or year-round living.',
                'description_fr' => 'Charmant appartement en bord de mer dans la ville balnéaire populaire de Martil. Parfait pour locations estivales ou résidence permanente.',
                'price' => 6500,
                'transaction_type' => 'rent',
                'property_type' => 'apartment',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area_sqm' => 70,
                'floor' => '2nd',
                'furnished' => 'furnished',
                'city' => 'Martil',
                'neighborhood' => 'Beachfront',
                'latitude' => 35.6167,
                'longitude' => -5.2667,
                'featured' => false,
                'status' => 'published',
            ],
            [
                'title_en' => 'Mountain View Apartment in Tetouan',
                'title_fr' => 'Appartement vue montagne à Tétouan',
                'description_en' => 'Beautiful apartment with views of the Rif Mountains. Modern interior, quiet neighborhood, close to the historic medina.',
                'description_fr' => 'Bel appartement avec vue sur les montagnes du Rif. Intérieur moderne, quartier calme, proche de la médina historique.',
                'price' => 5000,
                'transaction_type' => 'rent',
                'property_type' => 'apartment',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area_sqm' => 80,
                'floor' => '4th',
                'furnished' => 'semi-furnished',
                'city' => 'Tetouan',
                'neighborhood' => 'Centre',
                'latitude' => 35.5711,
                'longitude' => -5.3728,
                'featured' => false,
                'status' => 'published',
            ],

            // More Sale properties
            [
                'title_en' => 'Investment Apartment in Tangier Free Zone',
                'title_fr' => 'Appartement investissement Zone Franche de Tanger',
                'description_en' => 'New development near the Tangier Free Zone, ideal for rental investment. High demand area with growing infrastructure.',
                'description_fr' => 'Nouveau développement près de la Zone Franche de Tanger, idéal pour investissement locatif. Zone à forte demande avec infrastructure croissante.',
                'price' => 650000,
                'transaction_type' => 'sale',
                'property_type' => 'apartment',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'area_sqm' => 50,
                'floor' => '3rd',
                'furnished' => 'unfurnished',
                'city' => 'Tangier',
                'neighborhood' => 'Zone Franche',
                'latitude' => 35.7234,
                'longitude' => -5.9012,
                'featured' => false,
                'status' => 'published',
            ],
            [
                'title_en' => 'Duplex Apartment in Hay Bendibane',
                'title_fr' => 'Appartement duplex à Hay Bendibane',
                'description_en' => 'Spacious duplex apartment with private entrance feel. Two levels of comfortable living space with modern finishes.',
                'description_fr' => 'Appartement duplex spacieux avec impression d\'entrée privée. Deux niveaux d\'espace de vie confortable avec finitions modernes.',
                'price' => 1100000,
                'transaction_type' => 'sale',
                'property_type' => 'apartment',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area_sqm' => 130,
                'floor' => '5th-6th',
                'furnished' => 'unfurnished',
                'city' => 'Tangier',
                'neighborhood' => 'Hay Bendibane',
                'latitude' => 35.7534,
                'longitude' => -5.8234,
                'featured' => false,
                'status' => 'published',
            ],
            [
                'title_en' => 'Luxury Villa in Jbel Kbir',
                'title_fr' => 'Villa de luxe à Jbel Kbir',
                'description_en' => 'Exclusive villa in the prestigious Jbel Kbir mountain area. Panoramic views, large garden, guest house, and security.',
                'description_fr' => 'Villa exclusive dans le prestigieux quartier montagneux de Jbel Kbir. Vues panoramiques, grand jardin, maison d\'hôtes et sécurité.',
                'price' => 8500000,
                'transaction_type' => 'sale',
                'property_type' => 'villa',
                'bedrooms' => 6,
                'bathrooms' => 5,
                'area_sqm' => 600,
                'floor' => null,
                'furnished' => 'furnished',
                'city' => 'Tangier',
                'neighborhood' => 'Jbel Kbir',
                'latitude' => 35.7912,
                'longitude' => -5.8567,
                'featured' => true,
                'status' => 'published',
            ],
            [
                'title_en' => 'Renovated Apartment in Dradeb',
                'title_fr' => 'Appartement rénové à Dradeb',
                'description_en' => 'Recently renovated apartment in the popular Dradeb area. New kitchen, bathroom, and flooring. Ready to move in.',
                'description_fr' => 'Appartement récemment rénové dans le quartier populaire de Dradeb. Nouvelle cuisine, salle de bain et revêtement de sol. Prêt à emménager.',
                'price' => 780000,
                'transaction_type' => 'sale',
                'property_type' => 'apartment',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area_sqm' => 65,
                'floor' => '3rd',
                'furnished' => 'unfurnished',
                'city' => 'Tangier',
                'neighborhood' => 'Dradeb',
                'latitude' => 35.7712,
                'longitude' => -5.7923,
                'featured' => false,
                'status' => 'published',
            ],
            [
                'title_en' => 'Beachfront Land in Sidi Kankouch',
                'title_fr' => 'Terrain bord de mer à Sidi Kankouch',
                'description_en' => 'Rare beachfront plot with direct beach access. Perfect for private villa or boutique hotel development.',
                'description_fr' => 'Rare parcelle en bord de mer avec accès direct à la plage. Parfait pour villa privée ou développement hôtel boutique.',
                'price' => 4500000,
                'transaction_type' => 'sale',
                'property_type' => 'land',
                'bedrooms' => null,
                'bathrooms' => null,
                'area_sqm' => 2000,
                'floor' => null,
                'furnished' => null,
                'city' => 'Tangier',
                'neighborhood' => 'Sidi Kankouch',
                'latitude' => 35.8012,
                'longitude' => -5.7234,
                'featured' => true,
                'status' => 'published',
            ],
            [
                'title_en' => 'Corner Shop in Souani',
                'title_fr' => 'Boutique d\'angle à Souani',
                'description_en' => 'Prime corner location shop in busy Souani commercial area. High visibility and foot traffic. Suitable for retail or food business.',
                'description_fr' => 'Boutique d\'angle de premier choix dans le quartier commercial animé de Souani. Grande visibilité et passage piéton. Adapté commerce ou restauration.',
                'price' => 1800000,
                'transaction_type' => 'sale',
                'property_type' => 'shop',
                'bedrooms' => null,
                'bathrooms' => 1,
                'area_sqm' => 60,
                'floor' => 'Ground',
                'furnished' => 'unfurnished',
                'city' => 'Tangier',
                'neighborhood' => 'Souani',
                'latitude' => 35.7689,
                'longitude' => -5.8012,
                'featured' => false,
                'status' => 'published',
            ],
        ];

        $features = [
            'balcony', 'terrace', 'garden', 'pool', 'parking', 'garage',
            'elevator', 'security', 'ac', 'heating', 'storage', 'gym'
        ];

        foreach ($properties as $index => $data) {
            $property = Property::create(array_merge($data, [
                'slug' => Str::slug($data['title_en']),
                'property_code' => 'TNG-' . str_pad($index + 1, 4, '0', STR_PAD_LEFT),
                'views' => rand(50, 500),
            ]));

            // No placeholder images - model will use Unsplash fallbacks

            // Add random features
            $selectedFeatures = array_rand(array_flip($features), rand(4, 8));
            foreach ($selectedFeatures as $feature) {
                PropertyFeature::create([
                    'property_id' => $property->id,
                    'feature_key' => $feature,
                    'value' => 'yes',
                ]);
            }
        }
    }
}
